{% set name = "qiskit-algorithms" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-algorithms-{{ version }}.tar.gz
  sha256: 53829402d53a2c8ef84db5a348c071e497a3bf5b45a017b8bf748cf9d9997db0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - qiskit >=0.44
    - python >=3.8
    - scipy >=1.4
    - numpy >=1.17

test:
  imports:
    - qiskit_algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiskit-community/qiskit-algorithms
  summary: 'Qiskit Algorithms: A library of quantum computing algorithms'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
