{% set name = "qiskit-algorithms" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qiskit-algorithms-{{ version }}.tar.gz
  sha256: 02eedcbb079c6da371421a50cb296ff1dc6ce4a1c478ec521ff6e62c9bc53e10

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - qiskit >=0.44
    - python >=3.8
    - scipy >=1.4
    - numpy >=1.17

test:
  imports:
    - qiskit_algorithms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/qiskit-community/qiskit-algorithms
  summary: 'Qiskit Algorithms: A library of quantum computing algorithms'
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
    - wshanks
